<<<<<<< HEAD
# Generated by Django 5.2.3 on 2026-05-16 06:07
=======
# Generated by Django 5.2.7 on 2026-05-22 13:51
>>>>>>> ee31cab66c0474900ecd8694bbe0aa38c2c4fc1b

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollments', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_enrollments', to='students.student'),
        ),
    ]
