# Generated by Django 5.1 on 2026-07-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableslot',
            name='lecturer_name_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
