# Generated by Django 5.2.7 on 2026-05-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        ('timetable', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = []
