# Generated by Django 5.1 on 2026-08-21 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_remove_timetableslot_curriculum_unit_and_more'),
        ('timetable', '0002_timetableslot_lecturer_name_text'),
    ]

    operations = [
    ]
