# Generated by Django 5.1 on 2026-09-22 20:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_alter_timetableslot_stream'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(help_text="Department the allocation came from, e.g. 'DEPARTMENT OF EDUCATION'.", max_length=150)),
                ('academic_year', models.CharField(max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('rows', models.JSONField(blank=True, default=list)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['academic_year', 'source'],
            },
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='allocation_document',
            field=models.ForeignKey(blank=True, help_text="Department allocation document whose row currently sets this slot's lecturer; blank when set by hand or not yet allocated.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_slots', to='timetable.allocationdocument'),
        ),
        migrations.AddConstraint(
            model_name='allocationdocument',
            constraint=models.UniqueConstraint(fields=('academic_year', 'source'), name='unique_allocation_source_per_year'),
        ),
    ]
