<<<<<<< HEAD
# Generated by Django 5.2.3 on 2026-05-16 06:07
=======
# Generated by Django 5.2.7 on 2026-05-22 13:51
>>>>>>> ee31cab66c0474900ecd8694bbe0aa38c2c4fc1b

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
<<<<<<< HEAD
=======
                ('name', models.CharField(max_length=255)),
>>>>>>> ee31cab66c0474900ecd8694bbe0aa38c2c4fc1b
                ('building', models.CharField(max_length=255)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('capacity', models.PositiveIntegerField()),
                ('room_type', models.CharField(choices=[('lecture_hall', 'Lecture Hall'), ('lab', 'Lab'), ('seminar', 'Seminar')], default='lecture_hall', max_length=30)),
<<<<<<< HEAD
=======
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Under Maintenance'), ('closed', 'Closed'), ('unavailable', 'Unavailable')], default='active', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('facilities', models.TextField(blank=True)),
>>>>>>> ee31cab66c0474900ecd8694bbe0aa38c2c4fc1b
            ],
            options={
                'ordering': ['building', 'code'],
            },
        ),
    ]
