# Generated by Django 5.1 on 2026-09-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
