name: Deploy SMARTTT Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy and restart services
        run: |
          # Navigate to project location on the VPS
          cd $GITHUB_WORKSPACE

          # Activate virtualenv and update dependencies
          source .venv/bin/activate
          pip install -r requirements.txt

          # Database migrations & static collection
          python manage.py migrate
          python manage.py collectstatic --noinput

          # Restart Gunicorn service
          sudo systemctl restart gunicorn
